projects:
  database:
    schemaPath: src/http/schema/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
  app:
    schemaPath: src/http/schema/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:3000